### ISSUE TITLE
features tracking

### ISSUE THREAD

**Issue by RecursiveError** [RecursiveError/ESPAT#1]
- [x] Drop main support to ESP8266
- [x] change recv active mode to passive mode
- [x] enable syslog for error info
- [x] Add "notify" method to receive data
- [x] add MAC cofiguration
- [x] add WIfI protocol cofiguration
- [x] add DHCP/static IP configuration
- [x] Organize code into multiple files
- [x] Add TCP timeout to Server
- [x] add  "remote" host info to client
- [ ] allow pre-configured WiFi (for security)
- [ ] #6
- [x] UART  config
- [ ] Add power management methods
- [ ] code quality
- [ ] #5
- [ ] #7
